### ISSUE TITLE
Select playlists to sync

### ISSUE THREAD

**Issue by andylundqvist** [PokerFacowaty/naps#1]
**Feature request**

The possibility to select specific playlists to sync (and not sync all of them). In my use case, I have hundreds of playlists in Navidrome and only need to sync a few locally.

Thank you for considering this.

**Comment by PokerFacowaty** [comment]
Added in https://github.com/PokerFacowaty/naps/commit/2815540df5638ced3ca333c4f3e7a0ba9193ac15, thanks for the request!
